### ISSUE TITLE
M5Touch.cpp - M5.Lcd.readPixel not existing

### ISSUE THREAD

**Issue by drschlaumeier** [Kongduino/M5Widgets#1]
Hallo,
I'm testing your widgets but I cannot compile.
M5Touch is not working.
I get error

` M5Touch.cpp:64:31: error: 'class ILI9341' has no member named 'readPixel'`

data[position] = M5.Lcd.readPixel(px + i, py + j);

????

**Comment by Kongduino** [comment]
Indeed. It belonged to a previous version of M5Stack. And didn't work anyway. Thanks. I updated M5Touch.cpp.
